# Generated by Django 6.0.4 on 2026-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_grid_lens_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('overview', 'Overview'), ('commercial', 'Commercial'), ('financial', 'Financial'), ('technical', 'Technical'), ('hr', 'Human Resource'), ('regulatory', 'Regulatory'), ('energy_account', 'Energy Account'), ('grid_lens', 'GridLens')], max_length=20, unique=True),
        ),
    ]
