# Generated by Django 6.0.4 on 2026-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seed_roles_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('overview', 'Overview'), ('commercial', 'Commercial'), ('financial', 'Financial'), ('technical', 'Technical'), ('hr', 'Human Resource'), ('regulatory', 'Regulatory'), ('energy_account', 'Energy Account'), ('grid_lens', 'GridLens'), ('tmo', 'TMO'), ('cto', 'CTO Dashboard')], max_length=20, unique=True),
        ),
    ]
