# Generated by Django 6.0.4 on 2026-08-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_section_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role', 'section__name']},
        ),
    ]
