# Generated by Django 6.0.4 on 2026-06-25 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_band_minimum_hours_priority_order'),
        ('simulator', '0002_pccconfig_simulationrun_nerc_kpi_breach_pcc_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederCommercialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('billing_efficiency_pct', models.DecimalField(decimal_places=2, default=99.0, help_text='ATC component: Energy_Billed / Energy_Input × 100. Captures technical and commercial losses.', max_digits=5)),
                ('collection_efficiency_pct', models.DecimalField(decimal_places=2, default=80.0, help_text='C component: Revenue_Collected / Revenue_Billed × 100. Captures cash collection performance.', max_digits=5)),
                ('monthly_revenue_target_ngn', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly revenue target in Naira for this feeder. Used to compute gap-to-target.', max_digits=18, null=True)),
                ('effective_from', models.DateField(help_text='Date from which this commercial profile applies.')),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, help_text="Reference e.g. 'NERC Q1 2025 KEDCO benchmark' or 'Internal audit Jan 2026'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feeder Commercial Profile',
                'verbose_name_plural': 'Feeder Commercial Profiles',
                'ordering': ['feeder__name'],
            },
        ),
        migrations.RenameIndex(
            model_name='simulationfeederresult',
            new_name='simulator_s_simulat_e661a3_idx',
            old_name='simulator_f_simulat_status_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationfeederresult',
            new_name='simulator_s_feeder__acfcba_idx',
            old_name='simulator_f_feeder_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationrun',
            new_name='simulator_s_simulat_8d231c_idx',
            old_name='simulator_s_simulat_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationrun',
            new_name='simulator_s_scenari_9ec39d_idx',
            old_name='simulator_s_scenari_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationrun',
            new_name='simulator_s_created_b275ad_idx',
            old_name='simulator_s_created_idx',
        ),
        migrations.AddField(
            model_name='simulationfeederresult',
            name='atcc_loss_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue potential − expected collection — ATC&C loss in Naira (₦)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='simulationfeederresult',
            name='billing_efficiency_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ATC component used: Energy_Billed / Energy_Input × 100', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='simulationfeederresult',
            name='collection_efficiency_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='C component used: Revenue_Collected / Revenue_Billed × 100', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='simulationfeederresult',
            name='expected_billing_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue potential × billing efficiency (₦)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='simulationfeederresult',
            name='expected_collection_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected billing × collection efficiency — cash KEDCO will actually receive (₦)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='simulationfeederresult',
            name='revenue_per_mwh_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected collection ÷ allocated MWh — feeder efficiency ranking metric (₦/MWh)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='simulationfeederresult',
            name='revenue_potential_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross revenue potential: allocated MWh × 1000 × tariff rate (₦)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='simulationfeederresult',
            name='tariff_rate_ngn_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Tariff rate used for this feeder's revenue calculation (₦/kWh)", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='revenue_per_mwh_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected collection per MWh allocated — efficiency ranking metric (₦/MWh)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='total_atcc_loss_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total ATC&C loss exposure in Naira (₦)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='total_expected_billing_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected billing after ATC losses applied (₦)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='total_expected_collection_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected cash collected after collection efficiency applied (₦)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='total_revenue_potential_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross revenue if 100% of allocated energy is billed and collected (₦)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='feedercommercialprofile',
            name='feeder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='common.feeder'),
        ),
    ]
