# Generated by Django 6.0.4 on 2026-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmo', '0003_tmo_daily_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMONetworkDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('kedco_allocation_mw', models.DecimalField(decimal_places=4, max_digits=10)),
                ('disco_offtake_mw', models.DecimalField(decimal_places=4, max_digits=10)),
                ('variance_mw', models.DecimalField(decimal_places=4, max_digits=10)),
                ('available_generation_mw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('source', models.CharField(choices=[('manual', 'Manual / Excel Import'), ('datanest', 'DataNest Sync')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='tmomonthlysegmenttarget',
            name='segment',
            field=models.CharField(choices=[('MDI', 'MD Industrial'), ('MDNI', 'MD Non-Industrial'), ('Regions', 'Regions')], db_index=True, max_length=10),
        ),
    ]
