# Generated by Django 6.0.4 on 2026-07-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmo', '0007_rename_tariff_to_per_kwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('33kv', '33KV Load Flow'), ('11kv', '11KV Load Flow')], db_index=True, max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('spreadsheet_id', models.CharField(help_text='Google Sheets file ID', max_length=100)),
                ('spreadsheet_url', models.URLField(help_text='Full Google Sheets URL', max_length=600)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_log', models.TextField(blank=True, help_text='Output from last sync run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'feed_type'],
                'unique_together': {('feed_type', 'year', 'month')},
            },
        ),
    ]
