# Generated by Django 6.0.4 on 2026-07-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_feeder_pl_segment'),
        ('tmo', '0010_sheet_alert_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMOFeederSupplyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('target_hours', models.DecimalField(decimal_places=2, help_text='Daily hours-of-supply target for this feeder', max_digits=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_targets', to='common.feeder')),
            ],
            options={
                'ordering': ['year', 'month', 'feeder__name'],
                'unique_together': {('feeder', 'year', 'month')},
            },
        ),
    ]
