# Generated by Django 6.0.4 on 2026-08-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_feedercouplingevent'),
        ('tmo', '0011_add_tmo_feeder_supply_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TMOFeederOutlierFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The specific day being filed against')),
                ('observed_mwh', models.DecimalField(decimal_places=4, help_text="The feeder's raw EnergyDelivered reading on this day, captured at filing time", max_digits=12)),
                ('feeder_median_mwh', models.DecimalField(decimal_places=4, help_text="This feeder's own historical baseline median at filing time, for reference", max_digits=12)),
                ('resolution', models.CharField(choices=[('confirmed_data_issue', 'Confirmed data issue'), ('genuine_spike', 'Genuine spike'), ('false_positive', 'False positive')], max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlier_flags', to='common.feeder')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_outlier_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-filed_at'],
                'constraints': [models.UniqueConstraint(fields=('feeder', 'date'), name='unique_outlier_flag_per_feeder_day')],
            },
        ),
    ]
