# Generated by Django 6.0.4 on 2026-08-09 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_feedercouplingevent'),
        ('tmo', '0012_tmofeederoutlierflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TMONegativeNetFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The specific day being filed against')),
                ('gross_mwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('children_sum_mwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('net_mwh', models.DecimalField(decimal_places=4, help_text='gross_mwh - children_sum_mwh, captured at filing time (always negative)', max_digits=12)),
                ('resolution', models.CharField(choices=[('needs_coupling_event', 'Needs a coupling event logged'), ('needs_topology_fix', 'Needs a permanent topology fix'), ('confirmed_data_issue', 'Confirmed data issue'), ('unresolved', 'Unresolved — still investigating')], max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_net_flags', to='common.feeder')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_negative_net_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-filed_at'],
                'constraints': [models.UniqueConstraint(fields=('feeder', 'date'), name='unique_negative_net_flag_per_feeder_day')],
            },
        ),
    ]
