# Generated by Django 6.0.4 on 2026-08-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmo', '0013_tmonegativenetflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(db_index=True, max_length=30)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('result', models.TextField(blank=True, help_text='Sync result summary, or error traceback on failure')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['feed_type', '-started_at'], name='tmo_sheetsy_feed_ty_62b11d_idx')],
            },
        ),
    ]
