# Generated by Django 6.0.4 on 2026-08-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmo', '0014_sheetsyncrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetfeed',
            name='feed_type',
            field=models.CharField(choices=[('33kv_load_flow', '33KV Load Flow'), ('33kv_energy_accounting', '33KV Energy Accounting'), ('11kv_load_flow', '11KV Load Flow'), ('11kv_energy_accounting', '11KV Energy Accounting'), ('tcn_33kv_fault_log', 'TCN 33KV Fault Log (yearly)')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='googlesheetfeed',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
