# Generated by Django 5.1.7 on 2025-07-26 22:32

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOverviewSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField(db_index=True, help_text='First day of the month (e.g., 2025-01-01)', unique=True)),
                ('revenue_billed', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue billed for the month', max_digits=15)),
                ('revenue_collected', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue collected for the month', max_digits=15)),
                ('customers_billed', models.PositiveIntegerField(default=0, help_text='Number of customers billed')),
                ('customers_responded', models.PositiveIntegerField(default=0, help_text='Number of customers who responded/paid')),
                ('energy_delivered', models.DecimalField(decimal_places=2, default=0, help_text='Total energy delivered in MWh', max_digits=12)),
                ('energy_billed', models.DecimalField(decimal_places=2, default=0, help_text='Total energy billed in MWh', max_digits=12)),
                ('energy_collected', models.DecimalField(decimal_places=2, default=0, help_text='Energy equivalent of collections in MWh', max_digits=12)),
                ('avg_hours_supply', models.DecimalField(decimal_places=2, default=0, help_text='Average hours of electricity supply per day', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('avg_interruption_duration', models.DecimalField(decimal_places=2, default=0, help_text='Average duration of interruptions in hours', max_digits=5)),
                ('avg_turnaround_time', models.DecimalField(decimal_places=2, default=0, help_text='Average time to restore power in hours', max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total operational cost for the month', max_digits=15)),
                ('total_opex', models.DecimalField(decimal_places=2, default=0, help_text='Total operational expenditure', max_digits=15)),
                ('total_salaries', models.DecimalField(decimal_places=2, default=0, help_text='Total salary payments', max_digits=15)),
                ('total_nbet', models.DecimalField(decimal_places=2, default=0, help_text='NBET invoice amount', max_digits=15)),
                ('total_mo', models.DecimalField(decimal_places=2, default=0, help_text='Market Operator invoice amount', max_digits=15)),
                ('billing_efficiency', models.DecimalField(decimal_places=2, default=0, help_text='Billing efficiency percentage (Energy Billed / Energy Delivered)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('collection_efficiency', models.DecimalField(decimal_places=2, default=0, help_text='Collection efficiency percentage (Revenue Collected / Revenue Billed)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('atc_losses', models.DecimalField(decimal_places=2, default=0, help_text='Aggregate Technical & Commercial losses percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('customer_response_rate', models.DecimalField(decimal_places=2, default=0, help_text='Customer response rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this summary was last calculated')),
                ('calculation_duration', models.DurationField(blank=True, help_text='How long the calculation took', null=True)),
                ('source_data_hash', models.CharField(blank=True, help_text='Hash of source data to detect changes and avoid unnecessary recalculations', max_length=64, null=True)),
                ('has_complete_data', models.BooleanField(default=True, help_text='Whether all required source data was available for calculation')),
            ],
            options={
                'verbose_name': 'Monthly Overview Summary',
                'verbose_name_plural': 'Monthly Overview Summaries',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='analytics_m_month_a6c7ae_idx'), models.Index(fields=['-month'], name='analytics_m_month_0ae3b4_idx'), models.Index(fields=['calculated_at'], name='analytics_m_calcula_d92a67_idx'), models.Index(fields=['has_complete_data', 'month'], name='analytics_m_has_com_a5f7a7_idx')],
            },
        ),
    ]
