# Generated by Django 5.1.7 on 2025-07-27 22:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('common', '0003_alter_distributiontransformer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTechnicalSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField(db_index=True, help_text='First day of the month (e.g., 2025-01-01)')),
                ('total_energy_delivered', models.DecimalField(decimal_places=4, default=0, help_text='Total energy delivered in MWh', max_digits=15)),
                ('avg_peak_load', models.DecimalField(decimal_places=2, default=0, help_text='Average peak load in MW', max_digits=10)),
                ('max_peak_load', models.DecimalField(decimal_places=2, default=0, help_text='Maximum peak load in MW', max_digits=10)),
                ('avg_hours_of_supply', models.DecimalField(decimal_places=2, default=0, help_text='Average hours of electricity supply per day', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('total_supply_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours of supply in the month', max_digits=8)),
                ('total_interruptions', models.PositiveIntegerField(default=0, help_text='Total number of interruptions')),
                ('avg_daily_interruptions', models.DecimalField(decimal_places=2, default=0, help_text='Average interruptions per day', max_digits=6)),
                ('avg_interruption_duration', models.DecimalField(decimal_places=2, default=0, help_text='Average duration of interruptions in hours', max_digits=6)),
                ('total_interruption_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours of interruptions', max_digits=10)),
                ('avg_turnaround_time', models.DecimalField(decimal_places=2, default=0, help_text='Average restoration time in hours', max_digits=6)),
                ('active_feeder_count', models.PositiveIntegerField(default=0, help_text='Number of active feeders')),
                ('total_customer_count', models.PositiveIntegerField(default=0, help_text='Total customers served')),
                ('load_shedding_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tcn_fault_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('equipment_fault_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('maintenance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_fault_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('saifi', models.DecimalField(decimal_places=4, default=0, help_text='System Average Interruption Frequency Index', max_digits=8)),
                ('saidi', models.DecimalField(decimal_places=4, default=0, help_text='System Average Interruption Duration Index', max_digits=8)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('calculation_duration', models.DurationField(blank=True, null=True)),
                ('has_complete_data', models.BooleanField(default=True)),
                ('business_district', models.ForeignKey(blank=True, help_text='Business district filter (null = all districts)', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.businessdistrict')),
                ('feeder', models.ForeignKey(blank=True, help_text='Specific feeder filter (null = all feeders)', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
                ('state', models.ForeignKey(blank=True, help_text='State filter (null = all states)', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.state')),
            ],
            options={
                'verbose_name': 'Monthly Technical Summary',
                'verbose_name_plural': 'Monthly Technical Summaries',
                'ordering': ['-month', 'state', 'business_district', 'feeder'],
                'indexes': [models.Index(fields=['month'], name='analytics_m_month_2896da_idx'), models.Index(fields=['-month'], name='analytics_m_month_93314d_idx'), models.Index(fields=['month', 'state'], name='analytics_m_month_d4541d_idx'), models.Index(fields=['month', 'business_district'], name='analytics_m_month_f2ca61_idx'), models.Index(fields=['month', 'feeder'], name='analytics_m_month_29d4ed_idx'), models.Index(fields=['calculated_at'], name='analytics_m_calcula_476373_idx'), models.Index(fields=['has_complete_data', 'month'], name='analytics_m_has_com_5c0deb_idx')],
                'unique_together': {('month', 'state', 'business_district', 'feeder')},
            },
        ),
    ]
