# Generated by Django 5.1.7 on 2025-07-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_monthlytechnicalsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlytechnicalsummary',
            old_name='tcn_fault_hours',
            new_name='line_fault_hours',
        ),
        migrations.AddField(
            model_name='monthlytechnicalsummary',
            name='avg_fault_turnaround_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average restoration time for actual faults (excluding load shedding)', max_digits=6),
        ),
        migrations.AddField(
            model_name='monthlytechnicalsummary',
            name='interruption_breakdown_json',
            field=models.JSONField(default=dict, help_text='Detailed breakdown of interruption hours by specific fault type'),
        ),
    ]
