# Generated by Django 5.1.7 on 2025-08-01 09:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_tcn_fault_hours_monthlytechnicalsummary_line_fault_hours_and_more'),
        ('common', '0003_alter_distributiontransformer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTechnicalSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date of the summary (e.g., 2025-01-15)')),
                ('total_energy_delivered', models.DecimalField(decimal_places=4, default=0, help_text='Total energy delivered in MWh for the day', max_digits=15)),
                ('avg_peak_load', models.DecimalField(decimal_places=2, default=0, help_text='Average peak load in MW for the day', max_digits=10)),
                ('max_peak_load', models.DecimalField(decimal_places=2, default=0, help_text='Maximum peak load in MW for the day', max_digits=10)),
                ('hours_of_supply', models.DecimalField(decimal_places=2, default=0, help_text='Hours of electricity supply for the day', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('total_interruptions', models.PositiveIntegerField(default=0, help_text='Total number of interruptions for the day')),
                ('avg_interruption_duration', models.DecimalField(decimal_places=2, default=0, help_text='Average duration of interruptions in hours', max_digits=6)),
                ('total_interruption_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours of interruptions for the day', max_digits=10)),
                ('avg_turnaround_time', models.DecimalField(decimal_places=2, default=0, help_text='Average restoration time in hours', max_digits=6)),
                ('active_feeder_count', models.PositiveIntegerField(default=0, help_text='Number of active feeders')),
                ('total_customer_count', models.PositiveIntegerField(default=0, help_text='Total customers served')),
                ('interruption_breakdown_json', models.JSONField(default=dict, help_text='Detailed breakdown of interruption hours by specific fault type')),
                ('load_shedding_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('equipment_fault_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('line_fault_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('maintenance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_fault_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_fault_turnaround_time', models.DecimalField(decimal_places=2, default=0, help_text='Average restoration time for actual faults (excluding load shedding)', max_digits=6)),
                ('saifi', models.DecimalField(decimal_places=4, default=0, help_text='System Average Interruption Frequency Index', max_digits=8)),
                ('saidi', models.DecimalField(decimal_places=4, default=0, help_text='System Average Interruption Duration Index', max_digits=8)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('calculation_duration', models.DurationField(blank=True, null=True)),
                ('has_complete_data', models.BooleanField(default=True)),
                ('business_district', models.ForeignKey(blank=True, help_text='Business district filter (null = all districts)', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.businessdistrict')),
                ('feeder', models.ForeignKey(blank=True, help_text='Specific feeder filter (null = all feeders)', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
                ('state', models.ForeignKey(blank=True, help_text='State filter (null = all states)', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.state')),
            ],
            options={
                'verbose_name': 'Daily Technical Summary',
                'verbose_name_plural': 'Daily Technical Summaries',
                'ordering': ['-date', 'state', 'business_district', 'feeder'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_121cfd_idx'), models.Index(fields=['-date'], name='analytics_d_date_674e60_idx'), models.Index(fields=['date', 'state'], name='analytics_d_date_9214d8_idx'), models.Index(fields=['date', 'business_district'], name='analytics_d_date_e31463_idx'), models.Index(fields=['date', 'feeder'], name='analytics_d_date_309c70_idx'), models.Index(fields=['calculated_at'], name='analytics_d_calcula_cc25d7_idx'), models.Index(fields=['has_complete_data', 'date'], name='analytics_d_has_com_d5ee42_idx')],
                'unique_together': {('date', 'state', 'business_district', 'feeder')},
            },
        ),
    ]
