# Generated by Django 5.1.7 on 2025-08-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_dailytechnicalsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytechnicalsummary',
            name='total_supply_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours of supply across all feeders for the day', max_digits=8),
        ),
    ]
