# Generated by Django 5.1.7 on 2026-02-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_dailytechnicalsummary_total_supply_hours'),
        ('common', '0005_powertransformer_feeder_feeder_class_feeder_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytechnicalsummary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytechnicalsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailytechnicalsummary',
            name='feeder_type',
            field=models.CharField(choices=[('11kv', '11kV'), ('33kv', '33kv')], default='11kv', help_text='Voltage level of the feeders included in this summary', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlyoverviewsummary',
            name='feeder_type',
            field=models.CharField(choices=[('11kv', '11kV'), ('33kv', '33kV')], default='11kv', help_text='Voltage level of the feeders included in this summary', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlytechnicalsummary',
            name='feeder_type',
            field=models.CharField(choices=[('11kv', '11kV'), ('33kv', '33kv')], default='11kv', help_text='Voltage level of the feeders included in this summary', max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlyoverviewsummary',
            name='month',
            field=models.DateField(db_index=True, help_text='First day of the month (e.g., 2025-01-01)'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytechnicalsummary',
            unique_together={('date', 'state', 'business_district', 'feeder', 'feeder_type')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyoverviewsummary',
            unique_together={('month', 'feeder_type')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlytechnicalsummary',
            unique_together={('month', 'state', 'business_district', 'feeder', 'feeder_type')},
        ),
        migrations.AddIndex(
            model_name='dailytechnicalsummary',
            index=models.Index(fields=['feeder_type'], name='analytics_d_feeder__a0f134_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyoverviewsummary',
            index=models.Index(fields=['feeder_type'], name='analytics_m_feeder__075513_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlytechnicalsummary',
            index=models.Index(fields=['feeder_type'], name='analytics_m_feeder__cec82a_idx'),
        ),
    ]
