# Generated by Django 5.1.7 on 2026-02-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_dailytechnicalsummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyoverviewsummary',
            name='energy_source',
            field=models.CharField(choices=[('meter_reading', 'Meter Reading'), ('system', 'System Fallback')], default='system', help_text='Source of the energy_delivered value', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlytechnicalsummary',
            name='energy_source',
            field=models.CharField(choices=[('meter_reading', 'Meter Reading'), ('system', 'System Fallback')], default='system', help_text='Source of the energy_delivered value', max_length=20),
        ),
    ]
