# Generated by Django 5.1.7 on 2025-11-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='is_onboarded',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this feeder has been onboarded to the system'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the feeder was onboarded', null=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, help_text='User who onboarded this feeder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_feeders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feeder',
            index=models.Index(fields=['is_onboarded'], name='common_feed_is_onbo_04af5a_idx'),
        ),
        migrations.AddIndex(
            model_name='feeder',
            index=models.Index(fields=['substation', 'is_onboarded'], name='common_feed_substat_67dec1_idx'),
        ),
    ]
