# Generated by Django 5.1.7 on 2026-02-23 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_feeder_is_onboarded_feeder_onboarded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerTransformer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity_mva', models.DecimalField(blank=True, decimal_places=2, help_text='Transformer capacity in MVA (e.g. 15.00, 7.50)', max_digits=5, null=True)),
                ('voltage_rating', models.CharField(blank=True, default='33/11kV', help_text="e.g. '33/11kV'", max_length=20)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100)),
                ('installation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=15)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feeder',
            name='feeder_class',
            field=models.CharField(blank=True, default='', help_text="Classification code e.g. '11K', '33K'", max_length=5),
        ),
        migrations.AddField(
            model_name='feeder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='injectionsubstation',
            name='state',
            field=models.ForeignKey(blank=True, help_text='State this station belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injection_substations', to='common.state'),
        ),
        migrations.AddField(
            model_name='injectionsubstation',
            name='station_type',
            field=models.CharField(choices=[('injection', 'Injection'), ('transmission', 'Transmission')], default='injection', help_text='Whether this is an injection substation (33/11kV) or transmission station (132/33kV)', max_length=15),
        ),
        migrations.AddField(
            model_name='injectionsubstation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='FeederSupplyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('supply_type', models.CharField(choices=[('primary', 'Primary'), ('backup', 'Backup'), ('emergency', 'Emergency'), ('parallel', 'Parallel')], default='primary', max_length=15)),
                ('supply_capacity_mw', models.DecimalField(blank=True, decimal_places=2, help_text='MW capacity for this supply relationship', max_digits=8, null=True)),
                ('priority_order', models.PositiveSmallIntegerField(default=1, help_text='1 = highest priority')),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('effective_until', models.DateTimeField(blank=True, help_text='NULL = currently active', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=15)),
                ('operational_notes', models.TextField(blank=True, default='')),
                ('supplied_feeder', models.ForeignKey(help_text='The feeder that receives power (typically 11kV)', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_feeders', to='common.feeder')),
                ('supplier_feeder', models.ForeignKey(help_text='The feeder that supplies power (typically 33kV)', on_delete=django.db.models.deletion.CASCADE, related_name='supplied_feeders', to='common.feeder')),
            ],
            options={
                'indexes': [models.Index(fields=['supplier_feeder', 'status'], name='common_feed_supplie_7f5d6b_idx'), models.Index(fields=['supplied_feeder', 'status'], name='common_feed_supplie_5b1040_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeederTransformerMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(blank=True, default='', help_text="e.g. 'primary', 'backup'", max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformer_mappings', to='common.feeder')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_mappings', to='common.powertransformer')),
            ],
            options={
                'unique_together': {('feeder', 'transformer')},
            },
        ),
    ]
