# Generated by Django 6.0.4 on 2026-04-30 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_feeder_commercial_onboarding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feeder',
            name='common_feed_commerc_idx',
        ),
    ]
