# Generated by Django 6.0.4 on 2026-08-09 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_feeder_pl_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederCouplingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('all', 'All downstream feeders'), ('selected', 'Selected feeders only')], default='all', help_text="Whether ALL of the faulted feeder's downstream network moved, or only specific feeders", max_length=10)),
                ('start_date', models.DateField(help_text="The date the coupling actually started, per TCN's own report — not the date this record was created")),
                ('end_date', models.DateField(blank=True, help_text='The date the coupling actually ended. Left blank while still open/ongoing.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_coupling_events', to=settings.AUTH_USER_MODEL)),
                ('coupled_to_feeder', models.ForeignKey(help_text="The feeder that temporarily took over the faulted feeder's downstream network", on_delete=django.db.models.deletion.CASCADE, related_name='coupling_events_as_coupled_to', to='common.feeder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_coupling_events', to=settings.AUTH_USER_MODEL)),
                ('faulted_feeder', models.ForeignKey(help_text='The feeder that went on fault and had its network coupled elsewhere', on_delete=django.db.models.deletion.CASCADE, related_name='coupling_events_as_faulted', to='common.feeder')),
                ('selected_feeders', models.ManyToManyField(blank=True, help_text="Only used when scope='selected' — the specific feeders that were coupled, rather than the faulted feeder's entire downstream network", related_name='coupling_events_as_selected_child', to='common.feeder')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['faulted_feeder', 'start_date', 'end_date'], name='common_feed_faulted_87dc29_idx'), models.Index(fields=['coupled_to_feeder', 'start_date', 'end_date'], name='common_feed_coupled_a1d9fc_idx')],
            },
        ),
    ]
