# Generated by Django 5.1.7 on 2025-09-22 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
        ('hr', '0004_alter_department_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='executive_role',
            field=models.CharField(blank=True, choices=[('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technology Officer'), ('CCO', 'Chief Commercial Officer'), ('CHRO', 'Chief Human Resources Officer')], help_text='Executive role if this staff member is a C-suite executive', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='kpi_targets_set',
            field=models.BooleanField(default=False, help_text='Whether KPI targets have been set for this executive'),
        ),
        migrations.AddField(
            model_name='staff',
            name='performance_review_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='quarterly', help_text="How frequently this executive's performance is reviewed", max_length=20),
        ),
        migrations.CreateModel(
            name='ExecutiveKPIDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('executive_role', models.CharField(choices=[('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technology Officer'), ('CCO', 'Chief Commercial Officer'), ('CHRO', 'Chief Human Resources Officer')], help_text='Which executive role this KPI belongs to', max_length=10)),
                ('category', models.CharField(choices=[('financial', 'Financial Excellence'), ('technical', 'Technical Operations'), ('commercial', 'Commercial Performance'), ('hr', 'Human Resources')], help_text='Category of the KPI', max_length=20)),
                ('name', models.CharField(help_text='Name of the KPI', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what this KPI measures')),
                ('data_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('currency', 'Currency (₦)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('ratio', 'Ratio')], help_text='Type of data this KPI represents', max_length=20)),
                ('unit', models.CharField(help_text='Unit of measurement (%, ₦, GWh, etc.)', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Priority level of this KPI', max_length=10)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, help_text='Single target value (for fixed targets)', max_digits=20, null=True)),
                ('target_min', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum target value (for range targets)', max_digits=20, null=True)),
                ('target_max', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum target value (for range targets)', max_digits=20, null=True)),
                ('is_range_target', models.BooleanField(default=False, help_text='Whether this KPI has a range target (min-max) or single target')),
                ('is_reverse_polarity', models.BooleanField(default=False, help_text='True if lower values are better (e.g., cost ratios, attrition)')),
                ('deadline', models.CharField(help_text="Target deadline (e.g., 'Q4 2025', 'Monthly', 'July 2025')", max_length=50)),
                ('measurement_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', help_text='How frequently this KPI is measured', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this KPI is currently being tracked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Executive KPI Definition',
                'verbose_name_plural': 'Executive KPI Definitions',
                'ordering': ['executive_role', 'category', 'priority', 'name'],
                'unique_together': {('executive_role', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExecutiveKPIAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('off_track', 'Off Track'), ('at_risk', 'At Risk'), ('deadline_approaching', 'Deadline Approaching'), ('target_missed', 'Target Missed'), ('exceptional_performance', 'Exceptional Performance')], max_length=30)),
                ('message', models.TextField(help_text='Alert message describing the issue')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is still active')),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether this alert has been acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('kpi_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hr.executivekpidefinition')),
            ],
            options={
                'verbose_name': 'Executive KPI Alert',
                'verbose_name_plural': 'Executive KPI Alerts',
                'ordering': ['-created_at', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='ExecutivePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('period_date', models.DateField(help_text='Date representing the period (first day of month/quarter/year)')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], help_text='Type of period this performance record represents', max_length=20)),
                ('actual_value', models.DecimalField(decimal_places=4, help_text='Actual achieved value', max_digits=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context for this performance record')),
                ('data_source', models.CharField(blank=True, help_text='Source of the data (manual entry, API, calculation, etc.)', max_length=100)),
                ('verified', models.BooleanField(default=False, help_text='Whether this data has been verified/approved')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_district', models.ForeignKey(blank=True, help_text='Specific business district if KPI is district-specific', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.businessdistrict')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performances', to=settings.AUTH_USER_MODEL)),
                ('kpi_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='hr.executivekpidefinition')),
                ('state', models.ForeignKey(blank=True, help_text='Specific state if KPI is state-specific', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.state')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Executive Performance Record',
                'verbose_name_plural': 'Executive Performance Records',
                'ordering': ['-period_date', 'kpi_definition'],
                'unique_together': {('kpi_definition', 'period_date', 'period_type', 'state', 'business_district')},
            },
        ),
    ]
