# Generated by Django 5.1.7 on 2025-12-08 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_staff_executive_role_staff_kpi_targets_set_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_title', models.CharField(max_length=255)),
                ('report_subtitle', models.CharField(blank=True, max_length=255)),
                ('report_type', models.CharField(choices=[('kpi', 'Board KPI Only'), ('hr_metrics', 'HR Metrics Only'), ('combined', 'Combined KPI + HR')], default='combined', max_length=50)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('sections', models.JSONField(default=list)),
                ('default_filters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_report_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HRReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('filters_used', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_hr_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.hrreporttemplate')),
            ],
            options={
                'db_table': 'hr_report_history',
                'ordering': ['-generated_at'],
            },
        ),
    ]
