# Generated by Django 5.1.7 on 2025-12-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_hrreporttemplate_hrreporthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrreporttemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='HRReportHistory',
        ),
        migrations.DeleteModel(
            name='HRReportTemplate',
        ),
    ]
