# Generated by Django 5.1.7 on 2025-11-24 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_title', models.CharField(default='Monthly Performance Report', max_length=255)),
                ('report_subtitle', models.CharField(blank=True, max_length=255)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=255)),
                ('filters_used', models.JSONField(default=dict)),
                ('sections_included', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('cover_page', 'Cover Page'), ('infrastructure_overview', 'Infrastructure Overview'), ('technical_metrics', 'Technical Metrics Cards'), ('system_reliability', 'System Reliability'), ('interruption_breakdown', 'Interruption Breakdown Table'), ('hours_of_supply_chart', 'Hours of Supply Chart'), ('load_trend_chart', 'Load Trend Chart'), ('energy_delivered_chart', 'Energy Delivered Chart'), ('feeder_performance_table', 'Feeder Performance Table'), ('state_performance_table', 'State Performance Table'), ('district_performance_table', 'District Performance Table'), ('service_band_summary', 'Service Band Summary'), ('custom_text', 'Custom Text/Notes'), ('gaps_improvements', 'Gaps and Improvement Areas'), ('commercial_summary', 'Commercial Summary'), ('financial_summary', 'Financial Summary'), ('collection_efficiency', 'Collection Efficiency')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('show_chart', models.BooleanField(default=False)),
                ('chart_type', models.CharField(blank=True, max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
    ]
