# Generated by Django 5.1.7 on 2025-12-10 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Performance'), ('commercial', 'Commercial Performance'), ('financial', 'Financial Performance'), ('hr', 'Human Resources'), ('executive', 'Executive Performance'), ('general', 'General Report')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Performance'), ('commercial', 'Commercial Performance'), ('financial', 'Financial Performance'), ('hr', 'Human Resources'), ('executive', 'Executive Performance'), ('general', 'General Report')], default='general', help_text='Type of report (Technical, HR, Executive, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='section_type',
            field=models.CharField(choices=[('cover_page', 'Cover Page'), ('infrastructure_overview', 'Infrastructure Overview'), ('technical_metrics', 'Technical Metrics Cards'), ('system_reliability', 'System Reliability'), ('interruption_breakdown', 'Interruption Breakdown Table'), ('hours_of_supply_chart', 'Hours of Supply Chart'), ('load_trend_chart', 'Load Trend Chart'), ('energy_delivered_chart', 'Energy Delivered Chart'), ('feeder_performance_table', 'Feeder Performance Table'), ('state_performance_table', 'State Performance Table'), ('district_performance_table', 'District Performance Table'), ('service_band_summary', 'Service Band Summary'), ('hr_overview', 'HR Overview'), ('staff_metrics', 'Staff Metrics Cards'), ('department_headcount', 'Headcount by Department'), ('staff_productivity', 'Staff Productivity Metrics'), ('wage_bill_analysis', 'Wage Bill Analysis'), ('attrition_analysis', 'Attrition Analysis'), ('recruitment_summary', 'Recruitment Summary'), ('training_summary', 'Training & Development Summary'), ('performance_appraisals', 'Performance Appraisals Summary'), ('executive_overview', 'Executive Performance Overview'), ('cfo_performance', 'CFO Performance Metrics'), ('cto_performance', 'CTO Performance Metrics'), ('cco_performance', 'CCO Performance Metrics'), ('chro_performance', 'CHRO Performance Metrics'), ('executive_kpi_summary', 'Executive KPI Summary Table'), ('executive_comparison', 'Executive Performance Comparison'), ('board_kpi_status', 'Board KPI Status'), ('kpi_trends', 'KPI Trends Over Time'), ('custom_text', 'Custom Text/Notes'), ('gaps_improvements', 'Gaps and Improvement Areas'), ('commercial_summary', 'Commercial Summary'), ('financial_summary', 'Financial Summary'), ('collection_efficiency', 'Collection Efficiency')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['category', 'generated_at'], name='reports_gen_categor_39a1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by', 'category'], name='reports_gen_generat_4ccd15_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['category', 'status'], name='reports_rep_categor_6954e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['created_by', 'category'], name='reports_rep_created_5d03b8_idx'),
        ),
    ]
