# Generated by Django 5.1.7 on 2025-11-16 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
        ('technical', '0003_feederenergydaily_feederenergymonthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeMeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reading_date', models.DateField(db_index=True)),
                ('cumulative_mwh', models.DecimalField(decimal_places=4, help_text='Cumulative meter reading in MWh (like an odometer)', max_digits=15)),
                ('reading_time', models.DateTimeField(blank=True, help_text='Exact time of meter reading', null=True)),
                ('is_estimated', models.BooleanField(default=False, help_text='Flag if this reading is estimated (e.g., for missing data)')),
                ('notes', models.TextField(blank=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='common.feeder')),
            ],
            options={
                'ordering': ['feeder', 'reading_date'],
                'indexes': [models.Index(fields=['feeder', 'reading_date'], name='technical_c_feeder__922883_idx'), models.Index(fields=['reading_date'], name='technical_c_reading_b35b07_idx')],
                'unique_together': {('feeder', 'reading_date')},
            },
        ),
    ]
