# Generated by Django 5.1.7 on 2025-11-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0004_cumulativemeterreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydelivered',
            name='calculation_method',
            field=models.CharField(choices=[('meter_difference', 'Calculated from meter difference'), ('manual_entry', 'Manually entered'), ('estimated', 'Estimated from historical data')], default='meter_difference', max_length=50),
        ),
        migrations.AddField(
            model_name='energydelivered',
            name='is_calculated',
            field=models.BooleanField(default=True, help_text='True if calculated from meter readings, False if manually entered'),
        ),
        migrations.AlterField(
            model_name='energydelivered',
            name='energy_mwh',
            field=models.DecimalField(decimal_places=2, help_text='ACTUAL energy delivered on this date (not cumulative)', max_digits=10),
        ),
    ]
