# Generated by Django 5.1.7 on 2025-11-17 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
        ('technical', '0005_energydelivered_calculation_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energydelivered',
            options={'ordering': ['date', 'feeder']},
        ),
        migrations.AlterModelOptions(
            name='feederinterruption',
            options={'ordering': ['-occurred_at']},
        ),
        migrations.AlterModelOptions(
            name='hourlyload',
            options={'ordering': ['date', 'hour']},
        ),
        migrations.AddField(
            model_name='hourlyload',
            name='reading_time',
            field=models.TimeField(blank=True, help_text='Precise time of reading (HH:MM:SS) for sub-hour accuracy', null=True),
        ),
        migrations.AlterField(
            model_name='feederinterruption',
            name='feeder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interruptions', to='common.feeder'),
        ),
        migrations.AlterField(
            model_name='feederinterruption',
            name='interruption_type',
            field=models.CharField(choices=[('E/F', 'Earth Fault'), ('O/C', 'Overcurrent'), ('O/C & E/F', 'Overcurrent and Earth Fault'), ('NO RI', 'No RI'), ('N/A', 'Not Specified'), ('L/S', 'Load Shedding (L/S)'), ('O/S', 'Overload/Overcurrent (O/S)'), ('T/F', 'Transformer Fault (T/F)'), ('B/F', 'Bus/Breakdown Fault (B/F)'), ('O/N', 'Overheating/Overtemp (O/N)'), ('O/E', 'Open Earth (O/E)'), ('P/O', 'Phase Open (P/O)'), ('O/F', 'Over Frequency (O/F)'), ('P/M', 'Phase Missing/Phase Metering (P/M)'), ('O', 'Other Faults/Operational Fault (O)'), ('T/S', 'Trip/Surge Fault (T/S)'), ('L/S GS', 'Load Shedding – General Supply (L/S GS)'), ('MTNC', 'Maintenance (MTNC)'), ('OC & E/F', 'Open Circuit & Earth Fault (OC & E/F)'), ('EM/D', 'Emergency/Device (EM/D)'), ('330KV L/F', '330 kV Line Fault (330KV L/F)'), ('OFF', 'Switch Off/Feeder Off (OFF)'), ('S/C', 'Short Circuit (S/C)'), ('132KV E/F', '132 kV Earth Fault (132KV E/F)'), ('132KV L/F', '132 kV Line Fault (132KV L/F)'), ('330KV L/S', '330 kV Line Shelving/Load Shedding (330KV L/S)'), ('132KV CB/F', '132 kV Circuit Breaker Failure (132KV CB/F)'), ('D/C', 'Double Circuit/Direct Current (D/C)'), ('MTCE', 'Maintenance (MTCE)'), ('IN O/C', 'Incoming Over Current/Infeeder OC (IN O/C)'), ('T/LS', 'Thermal Load Shedding (T/LS)'), ('132KV MTCE', '132 kV Maintenance (132KV MTCE)'), ('LIM', 'Lightning Impulse/Limit (LIM)'), ('tcn', '(tcn)'), ('fault', 'Fault'), ('permit', 'Permit')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feederinterruption',
            name='occurred_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='energydelivered',
            index=models.Index(fields=['date'], name='technical_e_date_8a72c3_idx'),
        ),
        migrations.AddIndex(
            model_name='energydelivered',
            index=models.Index(fields=['feeder', 'date'], name='technical_e_feeder__565003_idx'),
        ),
        migrations.AddIndex(
            model_name='feederinterruption',
            index=models.Index(fields=['occurred_at'], name='technical_f_occurre_7d6ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='feederinterruption',
            index=models.Index(fields=['interruption_type', 'occurred_at'], name='technical_f_interru_6ad2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='feederinterruption',
            index=models.Index(fields=['feeder', 'occurred_at'], name='technical_f_feeder__488d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyload',
            index=models.Index(fields=['date', 'hour'], name='technical_h_date_147b82_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyload',
            index=models.Index(fields=['feeder', 'date'], name='technical_h_feeder__7dcfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyload',
            index=models.Index(fields=['date'], name='technical_h_date_8930ce_idx'),
        ),
    ]
