# Generated by Django 5.1.7 on 2026-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_powertransformer_feeder_feeder_class_feeder_status_and_more"),
        ("technical", "0008_seed_disco_fault_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="cumulativemeterreading",
            name="is_late",
            field=models.BooleanField(
                default=False,
                help_text="True if this submission was made after the allowed submission window",
            ),
        ),
        migrations.AddField(
            model_name="cumulativemeterreading",
            name="is_suspicious",
            field=models.BooleanField(
                default=False,
                help_text="Flagged by DataNest as a suspicious reading (e.g. abnormal value)",
            ),
        ),
        migrations.AddField(
            model_name="cumulativemeterreading",
            name="original_submit_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The actual datetime the DSO submitted this record in DataNest",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cumulativemeterreading",
            name="submission_type",
            field=models.CharField(
                blank=True,
                choices=[("dso", "DSO"), ("admin_override", "Admin Override")],
                default="dso",
                help_text="Who submitted this record: dso (field officer) or admin_override",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hourlyload",
            name="is_late",
            field=models.BooleanField(
                default=False,
                help_text="True if this submission was made after the allowed submission window",
            ),
        ),
        migrations.AddField(
            model_name="hourlyload",
            name="original_submit_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The actual datetime the DSO submitted this record in DataNest",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hourlyload",
            name="submission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dso", "DSO"),
                    ("admin_override", "Admin Override"),
                    ("auto_cron", "Auto Cron"),
                ],
                default="dso",
                help_text="Who submitted this record: dso (field officer), admin_override, or auto_cron",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="cumulativemeterreading",
            index=models.Index(
                fields=["is_late"], name="technical_c_is_late_79965e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cumulativemeterreading",
            index=models.Index(
                fields=["submission_type"], name="technical_c_submiss_9a3ab5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hourlyload",
            index=models.Index(
                fields=["is_late"], name="technical_h_is_late_fe7085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hourlyload",
            index=models.Index(
                fields=["submission_type"], name="technical_h_submiss_44055b_idx"
            ),
        ),
    ]
