# Generated by Django 6.0.4 on 2026-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0011_datasynclog_records_deleted'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datasynclog',
            new_name='technical_d_data_ty_d92d17_idx',
            old_name='tech_synclog_type_started_idx',
        ),
        migrations.AlterField(
            model_name='datasynclog',
            name='data_type',
            field=models.CharField(choices=[('technical_hourly_load', 'Technical — Hourly Load'), ('technical_meter_readings', 'Technical — Meter Readings'), ('technical_interruptions', 'Technical — Interruptions'), ('ea_nbet_rates', 'EA — NBET Market Bilateral Rates'), ('ea_settings', 'EA — Settings'), ('ea_grid_meters', 'EA — Grid Meters'), ('ea_monthly_returns', 'EA — Monthly Returns'), ('ea_monthly_readings', 'EA — Monthly Readings'), ('ea_feeder_technical_energy', 'EA — Feeder Technical Energy'), ('ea_tcn_reconciliation', 'EA — TCN Reconciliation'), ('ea_tcn_reconciliation_notes', 'EA — TCN Reconciliation Notes'), ('ea_mo_reconciliation', 'EA — MO Reconciliation'), ('ea_weekly_readings', 'EA — Weekly Readings'), ('ea_station_assignments', 'EA — Station Assignments'), ('ea_meter_check_schedules', 'EA — Meter Check Schedules'), ('ea_meter_check_records', 'EA — Meter Check Records'), ('ea_coupling_log', 'EA — Coupling Log'), ('commercial_readings', 'Commercial — Meter Readings'), ('commercial_customers', 'Commercial — Customers'), ('commercial_managers', 'Commercial — Managers & Assignments'), ('commercial_tariff_rates', 'Commercial — Tariff Rates')], db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='feederinterruption',
            name='interruption_type',
            field=models.CharField(choices=[('E/F', 'Earth Fault'), ('O/C', 'Overcurrent'), ('O/C & E/F', 'Overcurrent and Earth Fault'), ('NO RI', 'No RI'), ('N/A', 'Not Specified'), ('L/S', 'Load Shedding (L/S)'), ('O/S', 'Overload/Overcurrent (O/S)'), ('T/F', 'Transformer Fault (T/F)'), ('B/F', 'Bus/Breakdown Fault (B/F)'), ('O/N', 'Overheating/Overtemp (O/N)'), ('O/E', 'Open Earth (O/E)'), ('P/O', 'Phase Open (P/O)'), ('O/F', 'Over Frequency (O/F)'), ('P/M', 'Phase Missing/Phase Metering (P/M)'), ('O', 'Other Faults/Operational Fault (O)'), ('T/S', 'Trip/Surge Fault (T/S)'), ('L/S GS', 'Load Shedding – General Supply (L/S GS)'), ('MTNC', 'Maintenance (MTNC)'), ('OC & E/F', 'Open Circuit & Earth Fault (OC & E/F)'), ('EM/D', 'Emergency/Device (EM/D)'), ('330KV L/F', '330 kV Line Fault (330KV L/F)'), ('OFF', 'Switch Off/Feeder Off (OFF)'), ('S/C', 'Short Circuit (S/C)'), ('132KV E/F', '132 kV Earth Fault (132KV E/F)'), ('L/F', 'Line Fault (L/F)'), ('132KV L/F', '132 kV Line Fault (132KV L/F)'), ('330KV L/S', '330 kV Line Shelving/Load Shedding (330KV L/S)'), ('132KV CB/F', '132 kV Circuit Breaker Failure (132KV CB/F)'), ('D/C', 'Double Circuit/Direct Current (D/C)'), ('MTCE', 'Maintenance (MTCE)'), ('IN O/C', 'Incoming Over Current/Infeeder OC (IN O/C)'), ('T/LS', 'Thermal Load Shedding (T/LS)'), ('132KV MTCE', '132 kV Maintenance (132KV MTCE)'), ('LIM', 'Lightning Impulse/Limit (LIM)'), ('tcn', '(tcn)'), ('fault', 'Fault'), ('permit', 'Permit')], db_index=True, max_length=100),
        ),
    ]
