# Generated by Django 6.0.4 on 2026-08-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0012_rename_tech_synclog_type_started_idx_technical_d_data_ty_d92d17_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydelivered',
            name='calculation_method',
            field=models.CharField(choices=[('meter_difference', 'Calculated from meter difference'), ('manual_entry', 'Manually entered'), ('estimated', 'Estimated from historical data'), ('sheet_variance', 'PRESENT − PREVIOUS energy column from source sheet')], default='meter_difference', max_length=50),
        ),
    ]
