# Generated by Django 6.0.4 on 2026-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0013_alter_energydelivered_calculation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyload',
            name='fault_code',
            field=models.CharField(blank=True, help_text="Raw fault/outage/maintenance code exactly as written in the source sheet when load_mw=0 was derived from a non-numeric cell (e.g. 'EF', 'O/C', 'TR2/F', 'MTC/DISC') — never normalised at write time, since the source is inconsistent about spelling. Only populated for sheet-derived (admin_override) rows; DataNest (dso) doesn't supply a reason with its zeros. See tmo.sheet_sync.FAULT_CODE_CATEGORIES for the read-time normalisation used to group these for reporting.", max_length=32, null=True),
        ),
    ]
