# Generated by Django 6.0.4 on 2026-08-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0014_hourlyload_fault_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederinterruption',
            name='is_planned',
            field=models.BooleanField(default=False, help_text='True for a scheduled/planned outage, False for a forced fault.'),
        ),
        migrations.AddField(
            model_name='feederinterruption',
            name='load_at_fault_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='feederinterruption',
            name='officer_confirming_interruption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feederinterruption',
            name='officer_confirming_restoration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feederinterruption',
            name='party_responsible',
            field=models.CharField(blank=True, choices=[('DISCO', 'DISCO (KEDCO)'), ('TCN', 'TCN'), ('GENCO', 'GENCO')], help_text='Which party the fault is attributed to — ties to penalty accountability.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feederinterruption',
            name='source',
            field=models.CharField(choices=[('dso', 'DSO (DataNest)'), ('tcn', 'TCN')], db_index=True, default='dso', max_length=10),
        ),
        migrations.AddField(
            model_name='feederinterruption',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
