# Generated by Django 6.0.4 on 2026-08-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0015_feederinterruption_is_planned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feederinterruption',
            name='is_planned',
        ),
        migrations.AddField(
            model_name='feederinterruption',
            name='outage_class',
            field=models.CharField(blank=True, choices=[('FORCED', 'Forced'), ('EMERGENCY', 'Emergency'), ('PLANNED', 'Planned')], help_text='Forced / Emergency / Planned — kept as the real 3-way category, not collapsed to a boolean.', max_length=10, null=True),
        ),
    ]
