# Generated by Django 6.0.4 on 2026-08-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0017_alter_feederinterruption_interruption_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasynclog',
            name='data_type',
            field=models.CharField(choices=[('technical_hourly_load', 'Technical — Hourly Load'), ('technical_meter_readings', 'Technical — Meter Readings'), ('technical_interruptions', 'Technical — Interruptions'), ('technical_tcn_interruptions', 'Technical — TCN 33kV Interruptions'), ('ea_nbet_rates', 'EA — NBET Market Bilateral Rates'), ('ea_settings', 'EA — Settings'), ('ea_grid_meters', 'EA — Grid Meters'), ('ea_monthly_returns', 'EA — Monthly Returns'), ('ea_monthly_readings', 'EA — Monthly Readings'), ('ea_feeder_technical_energy', 'EA — Feeder Technical Energy'), ('ea_tcn_reconciliation', 'EA — TCN Reconciliation'), ('ea_tcn_reconciliation_notes', 'EA — TCN Reconciliation Notes'), ('ea_mo_reconciliation', 'EA — MO Reconciliation'), ('ea_weekly_readings', 'EA — Weekly Readings'), ('ea_station_assignments', 'EA — Station Assignments'), ('ea_meter_check_schedules', 'EA — Meter Check Schedules'), ('ea_meter_check_records', 'EA — Meter Check Records'), ('ea_coupling_log', 'EA — Coupling Log'), ('commercial_readings', 'Commercial — Meter Readings'), ('commercial_customers', 'Commercial — Customers'), ('commercial_managers', 'Commercial — Managers & Assignments'), ('commercial_tariff_rates', 'Commercial — Tariff Rates')], db_index=True, max_length=60),
        ),
    ]
