"""
Django settings for raven project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import pymysql
from decouple import config

pymysql.install_as_MySQLdb()
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-yi0c+o@)5!9sz$kg2rys_1&fib-az-*2tdj@iq=qtt%txick*^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,31.97.56.29,kedco-raven-backend-updated.onrender.com,staging.apiraven.raven-emrc.com,live.apiraven.raven-emrc.com'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'common',
    'commercial',
    'financial',
    'technical',
    'hr',
    'regulatory',
    'corsheaders',
    'analytics',
    'users',
    'reports',
    'notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'raven.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'raven.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Log database configuration values
import logging

logger = logging.getLogger(__name__)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'technical.views': {  # Replace with your actual app name
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# APP_ENV selects which DB variable set to use: "staging" or "production"
APP_ENV = config('APP_ENV', default='production')
_DB = 'STAGING' if APP_ENV == 'staging' else 'PRODUCTION'

db_name = config(f'{_DB}_DB_NAME')
db_user = config(f'{_DB}_DB_USER')
db_password = config(f'{_DB}_DB_PASSWORD')
db_host = config(f'{_DB}_DB_HOST', default='localhost')
db_port = config(f'{_DB}_DB_PORT', default='5432')

logger.info(f"[{APP_ENV}] DB: {db_name} @ {db_host}:{db_port} (user={db_user})")
logger.info(f"[{APP_ENV}] DB PASSWORD: {'*' * len(db_password) if db_password else 'NOT_SET'}")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_password,
        'HOST': db_host,
        'PORT': db_port,
        'CONN_MAX_AGE': 60,  # reuse connections for 60s — eliminates reconnect overhead
    },
    'external': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config(f'{_DB}_EX_DB_NAME', default='dataNestDB_KEDCO'),
        'USER': config(f'{_DB}_EX_DB_USER', default='root'),
        'PASSWORD': config(f'{_DB}_EX_DB_PASSWORD', default=''),
        'HOST': config(f'{_DB}_EX_DB_HOST', default=''),
        'PORT': config(f'{_DB}_EX_DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST_FRAMEWORK = {
#     'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
#     'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
# }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Raven API',
    'VERSION': '1.0.0',
}


CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = ['http://localhost:5173',
                        'http://localhost:8000', 
                        'https://staging.apiraven.raven-emrc.com', 
                        'https://live.apiraven.raven-emrc.com', 
                        'http://31.97.56.29', 
                        'https://api.raven-emrc.com', 
                        'https://kedco-raven-backend-updated.onrender.com', 
                        'https://staging-six-pi.vercel.app']


# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",
#     # ...
# ]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://kedco-raven-backend-updated.onrender.com",
    "https://kedco.raven-emrc.com",
    "https://staging.apiraven.raven-emrc.com",
    "https://live.apiraven.raven-emrc.com",
    "https://staging-six-pi.vercel.app"
]




# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # 7 days
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=60),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}


BASE_URL = config('BASE_URL')

# ── Cache (used for SSO handoff codes) ───────────────────────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/2'),
    }
}

# ── Keycloak SSO ──────────────────────────────────────────────────────────────
# Realm URL — used by middleware/sso_authenticate.py to fetch the RS256 public key
KEYCLOAK_REALM_URL = config('KEYCLOAK_REALM_URL', default='http://31.97.56.29:8083/realms/KEDCO')

# DataNest SSO exchange endpoint — Raven POSTs the one-time code here to get a Keycloak token (DataNest → Raven)
DATANEST_SSO_URL = config('DATANEST_SSO_URL', default='https://staging.apidatanest.raven-emrc.com/api/auth/sso/exchange')

# DataNest frontend URL — Raven redirects user here with a one-time code (Raven → DataNest)
DATANEST_FRONTEND_URL = config('DATANEST_FRONTEND_URL', default='https://staging.apidatanest.raven-emrc.com')


# ── Celery ────────────────────────────────────────────────────────────────────
CELERY_BROKER_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/2')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://127.0.0.1:6379/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Lagos'
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1


# ── Resend (Email) ─────────────────────────────────────────────────────────────
RESEND_API_KEY = config('RESEND_API_KEY', default='')
RESEND_FROM_EMAIL = config('RESEND_FROM_EMAIL', default='Raven EMRC <noreply@raven-emrc.com>')

# In staging, all outgoing emails are redirected to this address instead of real recipients
RESEND_TEST_EMAIL = config('RESEND_TEST_EMAIL', default='test@raven-emrc.com')