# Generated by Django 6.0.4 on 2026-08-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_faultalertfeederwatch_faultalertrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultalertfeederwatch',
            name='current_fault_category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='faultalertfeederwatch',
            name='current_fault_raw_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='faultalertfeederwatch',
            name='fault_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultalertfeederwatch',
            name='is_currently_faulted',
            field=models.BooleanField(default=False),
        ),
    ]
