# Generated by Django 5.1.7 on 2025-11-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_dailycollection_customers_collected_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyEnergyDelivered',
        ),
    ]
