# Generated by Django 5.1.7 on 2026-03-19 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0003_delete_dailyenergydelivered"),
        ("common", "0005_powertransformer_feeder_feeder_class_feeder_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycollection",
            name="customers_collected",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailycollection",
            name="vendor_name",
            field=models.CharField(
                choices=[
                    ("BuyPower.ng", "BuyPower.ng"),
                    ("Banahim.net", "Banahim.net"),
                    ("Bank", "Bank"),
                    ("Cash", "Cash"),
                    ("POS", "POS"),
                    ("powershop.ng", "powershop.ng"),
                    ("Remita", "Remita"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="monthlyrevenuebilled",
            name="customers_billed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CommercialCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.CharField(max_length=36, unique=True)),
                ("account_no", models.CharField(max_length=50, unique=True)),
                ("meter_number", models.CharField(blank=True, max_length=50)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_address", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("MDI", "MDI (Maximum Demand Installation)"),
                            ("MDNI", "MDNI (Non Maximum Demand)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("datanest_created_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commercial_customers",
                        to="common.businessdistrict",
                    ),
                ),
                (
                    "feeder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commercial_customers",
                        to="common.feeder",
                    ),
                ),
            ],
            options={
                "ordering": ["customer_name"],
            },
        ),
        migrations.CreateModel(
            name="TariffRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("A", "Band A"),
                            ("B", "Band B"),
                            ("C", "Band C"),
                            ("D", "Band D"),
                            ("E", "Band E"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("MDI", "MDI (Maximum Demand Installation)"),
                            ("MDNI", "MDNI (Non Maximum Demand)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rate_per_kwh", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "datanest_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ["band", "customer_type"],
                "unique_together": {("band", "customer_type", "effective_from")},
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.CharField(max_length=36, unique=True)),
                ("reading_date", models.DateField()),
                ("reading_time", models.TimeField(blank=True, null=True)),
                (
                    "previous_reading",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "present_reading",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "consumption",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "multiplier_factor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "billed_consumption",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tariff_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reading_type",
                    models.CharField(
                        choices=[("MDI", "MDI"), ("MDNI", "MDNI")], max_length=10
                    ),
                ),
                ("recorded_by_id", models.CharField(blank=True, max_length=36)),
                ("recorded_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("gps_location_name", models.CharField(blank=True, max_length=500)),
                ("has_proof", models.BooleanField(default=False)),
                ("observation", models.TextField(blank=True)),
                ("datanest_created_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="commercial.commercialcustomer",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_date"],
                "indexes": [
                    models.Index(
                        fields=["reading_date"], name="commercial__reading_661a87_idx"
                    ),
                    models.Index(
                        fields=["reading_type"], name="commercial__reading_7be8aa_idx"
                    ),
                    models.Index(
                        fields=["customer", "reading_date"],
                        name="commercial__custome_6a3866_idx",
                    ),
                ],
                "unique_together": {("customer", "reading_date")},
            },
        ),
    ]
