# Generated by Django 5.1.7 on 2026-03-19 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0004_refactor_commercial_models"),
        ("common", "0005_powertransformer_feeder_feeder_class_feeder_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeterManager",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.CharField(max_length=36, unique=True)),
                ("user_external_id", models.CharField(blank=True, max_length=36)),
                ("staff_id", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=255)),
                (
                    "manager_type",
                    models.CharField(
                        choices=[("MDI", "MDI"), ("MDNI", "MDNI")], max_length=10
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MeterManagerAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.CharField(max_length=36, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "feeder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_assignments",
                        to="common.feeder",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="commercial.metermanager",
                    ),
                ),
            ],
            options={
                "ordering": ["manager", "feeder"],
                "unique_together": {("manager", "feeder")},
            },
        ),
    ]
