# Generated by Django 6.0.4 on 2026-04-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0007_meterreading_ocr_audit_gis'),
        ('common', '0005_powertransformer_feeder_feeder_class_feeder_status_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commercialcustomer',
            new_name='commercial__custome_1531ee_idx',
            old_name='commercial_customer_type_idx',
        ),
        migrations.RenameIndex(
            model_name='commercialcustomer',
            new_name='commercial__is_bypa_7d3ba2_idx',
            old_name='commercial_is_bypass_idx',
        ),
        migrations.RenameIndex(
            model_name='meterreading',
            new_name='commercial__ocr_sta_1c882d_idx',
            old_name='commercial_mr_ocr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meterreading',
            new_name='commercial__audit_s_fd0c3a_idx',
            old_name='commercial_mr_audit_status_idx',
        ),
        migrations.AddField(
            model_name='commercialcustomer',
            name='meter_fault_logged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialcustomer',
            name='meter_fault_logged_by',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='commercialcustomer',
            name='meter_status',
            field=models.CharField(choices=[('active', 'Active'), ('faulty', 'Faulty'), ('missing', 'Missing'), ('bypassed', 'Bypassed')], default='active', help_text='Current meter status synced from DataNest', max_length=10),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='estimation_method',
            field=models.CharField(blank=True, help_text='Non-empty when DataNest estimated this reading rather than taking an actual meter read', max_length=30),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='fault_source',
            field=models.CharField(blank=True, choices=[('feeder_fault', 'Feeder Fault'), ('meter_fault', 'Meter Fault')], help_text='If this reading occurred during a fault — which type', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='submission_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late')], default='on_time', help_text='Whether the reading was submitted on time or late', max_length=10),
        ),
        migrations.AlterField(
            model_name='commercialcustomer',
            name='is_bypass',
            field=models.BooleanField(default=False, help_text="True if meter_status is 'bypassed' in DataNest"),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='gis_match',
            field=models.BooleanField(blank=True, help_text="True if GPS coordinates match the GIS reference point, False if they don't, None if unchecked", null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='OCR confidence score (0–1). Low confidence = unreliable extraction', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='commercialcustomer',
            index=models.Index(fields=['meter_status'], name='commercial__meter_s_f6a19b_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['submission_status'], name='commercial__submiss_befd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['fault_source'], name='commercial__fault_s_443438_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['estimation_method'], name='commercial__estimat_3b11e8_idx'),
        ),
    ]
