# Generated by Django 6.0.4 on 2026-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_add_meter_status_and_reading_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialComparisonCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('insights', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
