# Generated by Django 6.0.4 on 2026-07-22 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_add_comparison_cache'),
        ('common', '0008_band_minimum_hours_priority_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMOBillingEfficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tmo_id', models.IntegerField(help_text='DataNest tmo_id', unique=True)),
                ('scope_type', models.CharField(choices=[('feeder', 'Feeder'), ('district', 'District'), ('state', 'State')], db_index=True, max_length=20)),
                ('scope_code', models.CharField(max_length=100)),
                ('scope_label', models.CharField(blank=True, max_length=200)),
                ('period_month', models.DateField(db_index=True)),
                ('energy_delivered_gwh', models.DecimalField(decimal_places=4, max_digits=14)),
                ('energy_billed_gwh', models.DecimalField(decimal_places=4, max_digits=14)),
                ('target_revenue_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('set_by_user_id', models.CharField(blank=True, max_length=100)),
                ('dn_created_at', models.DateTimeField(blank=True, null=True)),
                ('dn_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period_month', 'scope_type', 'scope_label'],
                'indexes': [models.Index(fields=['period_month', 'scope_type'], name='commercial__period__610bef_idx')],
            },
        ),
        migrations.CreateModel(
            name='TMOCollectionTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tmo_id', models.IntegerField(help_text='DataNest tmo_id', unique=True)),
                ('segment_code', models.CharField(db_index=True, max_length=100)),
                ('sub_segment', models.CharField(max_length=100)),
                ('period_month', models.DateField(db_index=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('set_by_user_id', models.CharField(blank=True, max_length=100)),
                ('dn_created_at', models.DateTimeField(blank=True, null=True)),
                ('dn_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period_month', 'segment_code', 'sub_segment'],
                'indexes': [models.Index(fields=['period_month', 'segment_code'], name='commercial__period__5c8a69_idx')],
            },
        ),
        migrations.CreateModel(
            name='TMOFeederTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tmo_id', models.IntegerField(help_text='DataNest tmo_id', unique=True)),
                ('feeder_code', models.CharField(help_text='Raw DataNest feeder_id', max_length=100)),
                ('target_date', models.DateField(db_index=True)),
                ('target_mwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('set_by_user_id', models.CharField(blank=True, max_length=100)),
                ('dn_created_at', models.DateTimeField(blank=True, null=True)),
                ('dn_updated_at', models.DateTimeField(blank=True, null=True)),
                ('feeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tmo_targets', to='common.feeder')),
            ],
            options={
                'ordering': ['-target_date', 'feeder_code'],
                'indexes': [models.Index(fields=['target_date'], name='commercial__target__813aef_idx')],
            },
        ),
    ]
